generate fixture for PostGenerationMethodCall declaration
pytest-dev/pytest-factoryboy pull request #103
Opened 2020-12-22 14:21 UTC by skarzi

Closes #87 

This PR adds fixtures generation for all subclasses (except `RelatedFactory`) of `PostGenerationDeclaration` .
The fixture is generated from `attr_fixture` and it's simply passed as a `context.value` to declaration's `call()` method call, so for it will be available for:

+ `PostGeneration` in `function` as `extracted`
+ `PostGenerationMethodCall`  as  first argument of called method

2021-01-12 13:40 UTC, skarzi commented
@youtux I will be very grateful if you find some time to review this PR because such a change will make working with the `PostGenerationMethodCall` declaration much easier

2021-06-23 16:12 UTC, MRigal commented on tests/test_postgen_dependencies.py
> +    """Test fixture for ``PosGeneration`` declaration."""
typo PostGeneration

2021-06-23 16:12 UTC, MRigal commented on tests/test_postgen_dependencies.py
> +    """Test fixture for ``PosGeneration`` declaration."""
also below

2021-06-24 07:33 UTC, skarzi commented on tests/test_postgen_dependencies.py
> +    """Test fixture for ``PosGeneration`` declaration."""
thanks for a review ;)

2021-06-27 11:49 UTC, olegpidsadnyi approved these changes
looks ok to me

2021-11-03 10:28 UTC, skarzi commented
hi :wave: 

could you prepare a new release with this feature included? 
Of course, I can help if something else should be done/implemented before the new release

2022-05-11 15:14 UTC, skarzi commented
@youtux could you review this PR?

2022-05-11 15:40 UTC, youtux requested changes

2022-05-11 15:40 UTC, youtux commented on tests/test_postgen_dependencies.py
> +    assert foo._postgeneration_results.pop("baz")
We used to assert that `... is foo`

2022-05-11 15:40 UTC, youtux commented on tests/test_postgen_dependencies.py
> +)
You can make 2 different calls to parametrize. It should look more neat

2022-05-11 15:40 UTC, youtux commented on tests/test_postgen_dependencies.py
> +    #: Value that is expected at the constructor
Useless comment, you can just remove it

2022-05-11 15:40 UTC, youtux commented on pytest_factoryboy/fixture.py
> +from typing_extensions import Protocol
Unused?

2022-05-11 15:40 UTC, youtux commented on pytest_factoryboy/fixture.py
> +            value, factory.RelatedFactory
We do another isinstqnce(..., RelatedFactory) in the else branch. Can you invert this if-else, and do this kind of check instead:

```python
if instance(..., (SubFactory, RelatedFactory)):
    ...
elif isinstance(..., PostGeneration):
    ...
elif isinstance(..., PostGenenerationMethodCall)
    ...
else:
raise NotImplementedError(useful error message to the user)
```

2022-05-11 15:41 UTC, youtux commented
Sorry it took so long, I didn't have it under my radar

2022-05-13 17:58 UTC, youtux commented on tests/test_postgen_dependencies.py
> +    #: Value that is expected at the constructor
actually, nevermind

2022-05-13 18:17 UTC, youtux commented on tests/test_postgen_dependencies.py
> +    assert foo._postgeneration_results.pop("baz")
nevermind, we didn't. I added a test for it and marked as xfail, since it's not working at the moment

2022-05-13 18:23 UTC, youtux approved these changes

2022-05-13 18:26 UTC, merged

2022-05-14 16:43 UTC, skarzi commented
sorry for the delay from my side, but if you want I can add another PR with changes suggested by you

2022-05-15 07:06 UTC, youtux commented
No worries, I already applied the suggestion and merged the pr. also release a new version with this fix on pypi